-- Firm learning loop (docs/LEARNING_LOOP_ARCHITECTURE.md).
-- Portable SQL (Postgres + H2 PostgreSQL mode): ids are generated by the application,
-- clause text columns hold Jasypt-encrypted text, lists are stored as comma-separated text.

-- What each drafted article was built from (exposure log).
CREATE TABLE IF NOT EXISTS draft_clause_exposures (
    id              UUID PRIMARY KEY,
    document_id     UUID NOT NULL,
    clause_key      VARCHAR(64) NOT NULL,
    article         INTEGER NOT NULL,
    title           VARCHAR(255),
    template_id     VARCHAR(64),
    contract_type   VARCHAR(64),
    provenance      VARCHAR(20) NOT NULL,          -- FIRM_BANK | GOLDEN | LLM
    firm_clause_id  UUID,
    insight_ids     TEXT,
    generated_text  TEXT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_exposures_document ON draft_clause_exposures (document_id);
CREATE INDEX IF NOT EXISTS idx_exposures_created ON draft_clause_exposures (created_at);

-- AI text vs the lawyer's text for one article of a draft.
CREATE TABLE IF NOT EXISTS clause_edits (
    id              UUID PRIMARY KEY,
    document_id     UUID NOT NULL,
    clause_key      VARCHAR(64) NOT NULL,
    article         INTEGER NOT NULL,
    template_id     VARCHAR(64),
    ai_text         TEXT,
    final_text      TEXT,
    edit_ratio      DOUBLE PRECISION NOT NULL,
    version_number  INTEGER,
    is_final        BOOLEAN NOT NULL,
    reflected       BOOLEAN NOT NULL,
    captured_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_clause_edits_doc_clause UNIQUE (document_id, clause_key)
);
CREATE INDEX IF NOT EXISTS idx_clause_edits_captured ON clause_edits (captured_at);

-- Segmented clauses from firm documents, with a MinHash signature for clustering.
CREATE TABLE IF NOT EXISTS clause_observations (
    id              UUID PRIMARY KEY,
    document_id     UUID NOT NULL,
    clause_key      VARCHAR(64) NOT NULL,
    contract_type   VARCHAR(64) NOT NULL,
    text_enc        TEXT NOT NULL,
    text_sha256     VARCHAR(64) NOT NULL,
    minhash         TEXT NOT NULL,
    executed        BOOLEAN NOT NULL,
    observed_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_observations_doc_clause UNIQUE (document_id, clause_key)
);
CREATE INDEX IF NOT EXISTS idx_observations_group ON clause_observations (clause_key, contract_type);

-- Candidate and approved firm clauses.
CREATE TABLE IF NOT EXISTS firm_clauses (
    id                  UUID PRIMARY KEY,
    clause_key          VARCHAR(64) NOT NULL,
    contract_type       VARCHAR(64) NOT NULL,
    status              VARCHAR(20) NOT NULL,      -- CANDIDATE | APPROVED | REJECTED | RETIRED
    position            VARCHAR(20) NOT NULL,      -- PRIMARY | FALLBACK_1 | FALLBACK_2
    text_enc            TEXT NOT NULL,
    fingerprint         VARCHAR(64) NOT NULL,
    support_count       INTEGER NOT NULL,
    executed_count      INTEGER NOT NULL,
    source_document_ids TEXT,
    times_used          INTEGER NOT NULL,
    approved_by         VARCHAR(255),
    approved_at         TIMESTAMP WITH TIME ZONE,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_firm_clauses_lookup ON firm_clauses (clause_key, contract_type, status);
CREATE INDEX IF NOT EXISTS idx_firm_clauses_fingerprint ON firm_clauses (fingerprint);

-- Learned drafting preferences (evolving playbook bullets).
CREATE TABLE IF NOT EXISTS drafting_insights (
    id              UUID PRIMARY KEY,
    clause_key      VARCHAR(64) NOT NULL,
    contract_type   VARCHAR(64),
    content         TEXT NOT NULL,
    status          VARCHAR(20) NOT NULL,          -- PROPOSED | ACTIVE | RETIRED
    evidence_count  INTEGER NOT NULL,
    evidence_docs   TEXT,
    helpful_count   INTEGER NOT NULL,
    harmful_count   INTEGER NOT NULL,
    source          VARCHAR(20) NOT NULL,          -- EDIT_REFLECTION | MANUAL
    approved_by     VARCHAR(255),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_insights_lookup ON drafting_insights (clause_key, status);

-- Lawyer corrections of individual review answers.
CREATE TABLE IF NOT EXISTS review_disputes (
    id              UUID PRIMARY KEY,
    document_id     UUID NOT NULL,
    question_id     VARCHAR(100) NOT NULL,
    clause_type     VARCHAR(64),
    contract_type   VARCHAR(64),
    model_answer    VARCHAR(20),
    correct_answer  VARCHAR(20) NOT NULL,
    quote           TEXT,
    note            TEXT,
    disputed_by     VARCHAR(255),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_disputes_question ON review_disputes (question_id, created_at);

-- Per-question answer and dispute counts (review calibration).
CREATE TABLE IF NOT EXISTS question_calibration (
    id              UUID PRIMARY KEY,
    question_id     VARCHAR(100) NOT NULL,
    contract_type   VARCHAR(64) NOT NULL,
    answered        INTEGER NOT NULL,
    disputed        INTEGER NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_calibration_question UNIQUE (question_id, contract_type)
);
