package com.legalpartner.model.enums;

public enum AuditActionType {
    DOCUMENT_UPLOAD, DOCUMENT_VIEW, DOCUMENT_DELETE,
    AI_QUERY, AI_COMPARE, RISK_ASSESSMENT,
    AUDIT_VIEW, AUDIT_EXPORT,
    LOGIN_SUCCESS, LOGIN_FAILED, LOGOUT,
    PASSWORD_CHANGED, PASSWORD_RESET_REQUESTED,
    MFA_ENABLED, MFA_DISABLED,
    ACCOUNT_LOCKED
}
