package com.legalpartner.model.enums;

public enum AuditActionType {
    DOCUMENT_UPLOAD, DOCUMENT_VIEW, DOCUMENT_DELETE,
    AI_QUERY, AI_COMPARE, RISK_ASSESSMENT,
    AUDIT_VIEW, AUDIT_EXPORT,
    LOGIN_SUCCESS, LOGIN_FAILED, LOGOUT,
    PASSWORD_CHANGED, PASSWORD_RESET_REQUESTED,
    MFA_ENABLED, MFA_DISABLED,
    ACCOUNT_LOCKED,
    WORKFLOW_STARTED, WORKFLOW_COMPLETED, WORKFLOW_FAILED, WORKFLOW_CANCELLED,
    CONNECTOR_EMAIL_SENT, CONNECTOR_EMAIL_FAILED,
    CONNECTOR_SLACK_SENT, CONNECTOR_SLACK_FAILED,
    CONNECTOR_TEAMS_SENT, CONNECTOR_TEAMS_FAILED,
    CONNECTOR_WEBHOOK_SENT, CONNECTOR_WEBHOOK_FAILED,
    INTEGRATION_CONNECTED, INTEGRATION_DISCONNECTED,
    AGENT_ANALYSIS_TRIGGERED, AGENT_ANALYSIS_COMPLETED, AGENT_FINDING_REVIEWED
}
